name: Build LaTeX document
on:
  push:
    branches: [ "main", "ghactions" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compilar los apuntes
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: cd front-matter/portada/ && epstopdf UABLogo.eps && pdflatex portada.tex && cd .. && cd .. && make


      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDF
      #     path: main.pdf 

      # Rename
      - run: mv main.pdf ApuntsPublics.pdf

      # https://github.com/marketplace/actions/push-a-file-to-another-repository
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'ApuntsPublics.pdf'
          destination_repo: 'aurelm95/aurelm95.github.io'
          # destination_folder: ''
          user_email: 'aurelm95@gmail.com'
          user_name: 'aurelm95'
          commit_message: '[BOT]: Github Action: Actualizar apuntes'
      